config/routes.rb
Rails.application.routes.draw do
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :robots, except: [:new]
  get '/index_customer' => 'robots#index_customer'
  resources :prototypes, only: [:show]
  resources :users, except: [:index]
  resources :manufacturers, only: [:show]
  get '/tina' => 'entrances#tina'
  get '/login_tina' => 'entrances#login_tina'
  get '/' => 'entrances#home'
  get '/home2' => 'entrances#home2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :prototypes
  has_many :robots


  def self.names
    manufacturers_names
  end

  def inventory_robots
    robots.where(pending: false)
  end


  validates :name, presence: true

private

  def self.manufacturers_names
    manufacturers = HTTParty.get("http://jordankamin.com/robots_api/robots.json")
    name_array = []
    manufacturers.parsed_response["manufacturers"].each do |man|
      name_array << man["name"]
    end
    name_array
  end

end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :manufacturer

  validates_presence_of :height, :weight, :model_no, :manufacturer_id, :price
  validates_numericality_of :height, :weight
end

app/models/robot.rb
class Robot < ApplicationRecord
  belongs_to :manufacturer

  validates_presence_of :height, :weight, :model_no
  validates_numericality_of :height, :weight, :manufacturer_id
  validates_inclusion_of :pending, in: [true, false]

  def self.inventory
    Robot.where(pending: false)
  end
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_secure_password

  validates :first_name, :last_name, :email, :username, presence: true
  validates_inclusion_of :admin, in: [true, false]
  validates :email, :username, uniqueness: true

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/entrances_controller.rb
class EntrancesController < ApplicationController
  def home
    render "entrances/home", layout: 'home'
  end

  def home2
    render "entrances/home2", layout: 'home'
  end

  def tina
    render "entrances/tina", layout: 'home'
  end



  def login_tina
    render "entrances/login_tina", layout: 'home'
  end

end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index

  end


  def show
    if logged_in?
      @manufacturer = Manufacturer.find(params[:id])
      if current_user_commissioner
      else
        respond_to do |format|
          format.html { render '_show', layout: false}
          format.js
        end
      end
    else
      redirect_to '/'
    end
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  def show
    if current_user_commissioner
      @prototype = Prototype.find(params[:id])
      @manufacturer = Manufacturer.find(@prototype.manufacturer_id)
      respond_to do |format|
        format.html { render 'show', layout: false}
        format.js
      end
    elsif current_user
      redirect_to index_customer_path
    else
      redirect_to '/'
    end
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy]

  def index
    if logged_in?
      if current_user_commissioner
        @robots = Robot.all
        @manufacturers = Manufacturer.all
      else
        redirect_to index_customer_path
      end
    else
      redirect_to '/'
    end
  end

  def index_customer
    if !logged_in?
      redirect_to '/'
    end
  end

  def create
    @robot = Robot.create(robot_params)
    redirect_to robots_path
  end

  def show
    if current_user_commissioner
    elsif current_user
      respond_to do |format|
        format.html { render '_show' }
        format.js
      end
    else
      redirect_to '/'
    end
  end

  def edit
    if current_user_commissioner
    else
      redirect_to robots_path
    end
  end

  def update
    @robot.update(robot_params)
    redirect_to robot_path(@robot)
  end

  def destroy
    if current_user
      if !current_user_commissioner
        flash[:info] = "Check your email for your purchase confirmation"
        PurchaseMailer.purchase_email(current_user, @robot).deliver
      end
      @robot.destroy
      redirect_to robots_path
    else
      redirect_to '/'
    end
  end


  private

  def set_robot
    @robot = Robot.find(params[:id])
  end

  def robot_params
    params.require(:robot).permit(:designation, :height, :weight, :model_no, :pending, :manufacturer_id, :price)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
    render "new"
  end

  def create
    user = User.find_by(username: params_username)
    if user && user.authenticate(params_password)
      log_in(user)
      if current_user_commissioner
        redirect_to robots_path
      else
        redirect_to index_customer_path
      end
    else
      flash[:danger] = "You must be logged in with proper credentials"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "You are now logged out."
    redirect_to '/'
  end

  private
  def params_username
    session_params[:username]
  end

  def params_password
    session_params[:password]
  end

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user_commissioner

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      flash[:success] = "You are now a member!"
      redirect_to robots_path # page for shopping
    else
      flash[:danger] = "You must give the correct information to continue!"
      render "new"
    end
  end

  def edit
    if logged_in?
      @user = User.find(params[:id])
    else
      redirect_to '/'
    end
  end

  def update
    if logged_in?
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:notice] = "Changes saved!"
        redirect_to robots_path
      else
        render 'edit'
      end
    else
      redirect_to '/'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :payment_info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
  def get_inventory
    Robot.where(pending: false).sort_by{|robot| robot.designation }
  end

  def get_manufacturers
    manufacturers = []
    get_inventory.each do |robot|
      manufacturers << robot.manufacturer unless manufacturers.include? robot.manufacturer
    end
    manufacturers.sort_by{ |manu| manu.name }
  end
end

app/helpers/prototype_helper.rb
module PrototypeHelper
  def get_attributes_for_robot(prototype)
    attributes = {}
    attributes['height'] = prototype.height
    attributes['weight'] = prototype.weight
    attributes['model_no'] = prototype.model_no
    attributes['price'] = (prototype.price * 2)
    attributes['manufacturer_id'] = prototype.manufacturer_id
    attributes['pending'] = true
    attributes
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def current_user_commissioner
    return false unless current_user
    current_user.admin?
  end


  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    current_user = nil
  end

end

app/views/entrances/home.html.erb
 <div class='home-container'>
  <h1>WHAT ARE YOU?</h1>
  <div>
    <a href='/tina' class="button">martials arts master that likes to hang out near powerplants</a>
  </div>
  <div>
    <a href='/home2' class="button">totally normal, legal person</a>
  </div>
</div>

app/views/entrances/home2.html.erb
 <div class='home-container'>
  <h1>HOW LONG IS YOUR ARM?</h1>
  <div>
    <a href='/tina' class="button">Longer than standard human length.</a>
  </div>
  <div>
    <a href='/login_tina' class="button">Standard, human length.</a>
  </div>
</div>

app/views/entrances/login_tina.html.erb
<div class='home-container'>
<h1 >THIS IS NOT A WEBSITE</h1>
</div>
<a href='/users/new' class=' stealthy-register'>register</a>
<a href='/login' class='stealthy-login'>login</a>

app/views/entrances/tina.html.erb
<div class="home-container"
<h1 class='tina-container'>THIS IS NOT A WEBSITE</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PsklrMrfi</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </head>

  <body>
    <% if current_user_commissioner || current_user %>
      <div id="welcome_container">
        <p id="welcome"> Welcome, <%= current_user.first_name %> </p> |
        <%= link_to 'HOME', robots_path, class: 'home-link' %> |
        <%= link_to "Log out", logout_path, method: :delete, id: "log-out" %> |
        <%= link_to "Update Profile", edit_user_path(current_user) %>
      </div>
    <% else %>
      <h2 id="gtfo"> This is still not a website.</h2>
    <% end %>

    <%= yield %>
  </body>

  <div align='center'>

  </div>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GO AWAY</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |message_type, message| %>
      <h1 style="text-align:center"><div class="alert alert-<%= message_type %>"><%= message %></div></h1>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/purchase_mailer.text.erb
<%= yield %>

app/views/manufacturers/_show.html.erb
<section class="manufacturer-details">
  <% @manufacturer.inventory_robots.each do |robot| %>
    <h2><%= link_to robot.designation, robot, class: 'robot-link', id: "robot-info-link-#{robot.id}" %></h2>
  <% end %>
</section>

app/views/manufacturers/show.html.erb
<nav class="home_link">
  <h1><%= link_to 'PSKLRMRFI', robots_path, class: 'home-link' %></h1>
</nav>

<section class="individual-item-container">
  <h1><%= @manufacturer.name %></h1>

  <% @manufacturer.prototypes.each do |prototype| %>
    <h2><%= link_to prototype.model_no, prototype, remote: true, class: 'prototype-link', id: "prototype-info-link-#{prototype.id}" %></h2>
  <% end %>
</section>

app/views/prototypes/_show.html.erb
<div class='prototype-details'>
  <ul class='protoype-list'>
    <li>Manufactured by: <%= @manufacturer.name %></li>
    <li>Height: <%= @prototype.height %></li>
    <li>Weight: <%= @prototype.weight %></li>
    <li>Price: $<%= sprintf('%.2f', @prototype.price) %></li>
  </ul>

  <% @robot = Robot.new(get_attributes_for_robot(@prototype)) %>
  <%= form_for @robot, url: {action: "create", :controller=>"robots"} do |robot_form| %>
    <%= robot_form.hidden_field :model_no %>
    <%= robot_form.hidden_field :height %>
    <%= robot_form.hidden_field :weight %>
    <%= robot_form.hidden_field :pending %>
    <%= robot_form.hidden_field :manufacturer_id %>
    <%= robot_form.hidden_field :price %>
    <%= robot_form.submit("Order") %>
  <% end %>
</div>

app/views/prototypes/show.html.erb
<section class="individual-item-container prototype-details">
  <div id="prototype-container">
    <h2><%= @prototype.model_no %></h2>
    <%= render partial: 'show', locals: {prototype: @prototype} %>
  </div>
</section>

app/views/robots/_show.html.erb
<section class="robot-buy-details robot-section">


  <div class="center-show-info">
    <div align= 'center' class='robot_show_model_no'>
      Designation: <%= @robot.designation %>
    </div>

    <div align='center' class='robot_show_model_no'>
        Model No: <%= @robot.model_no %>
      </div>
    <div align='center'>
      Weight: <%= @robot.weight%> Tons
    </div>

    <div align='center'>
      Height: <%= @robot.height%> Yds
    </div>

    <div align='center'>
      Price: $<%= sprintf('%.2f', @robot.price) %>
    </div>

    <%= form_tag("/robots/#{@robot.id}", align: "center", method: "DELETE") do %>
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="pk_test_mpRcVQZIKraOHtQYKZFtv1db"
        data-amount='<%= @robot.price * 100 %>'
        data-name="Robot Purchase"
        data-description="<%= @robot.designation %>"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto">
      </script>
    <% end %>

  </section>

app/views/robots/edit.html.erb
<nav>
  <a class='home-link' href='/robots'>Home</a>
</nav>

<h4>
  Current Designation:
  <%= @robot.designation%>
</h4>

<%= form_tag("/robots/#{@robot.id}", method: "PATCH") do %>
  <%= label_tag(:designation, "New Designation") %>
  <%= text_field(:robot, :designation, value: nil) %>
  <%= hidden_field(:robot, :pending, value: false) %>
  <%= submit_tag("Re-designate") %>
<% end %>

<%= form_tag("/robots/#{@robot.id}", method: "DELETE") do %>
  <%= submit_tag("Remove")%>
<% end %>

app/views/robots/index.html.erb
<div class="home_link">
  <h1><%= link_to 'PSKLRMRFI', robots_path, class: 'home-link' %></h1>
</div>

<main id="main-homepage">
<div class="container centered">
  <ul class="nav nav-tabs">
    <li class="active"><a id="link1" href="#tab1" data-toggle="tab">Manufacturers</a></li>
    <li><a id="link2" href="#tab2" data-toggle="tab">Robots In Inventory</a></li>
    <li><a id="link3" href="#tab3" data-toggle="tab">Queue</a></li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane active" id="tab1">
      <section class="robots-section">
        <h3>Manufacturers</h3>
        <% @manufacturers.each do |manufacturer| %>
          <ul>
            <li>
            <%= link_to manufacturer.name, manufacturer %>
            </li>
          </ul>
        <% end %>
      </section>
    </div><!-- end tab-pane -->

    <div class="tab-pane" id="tab2">
      <section class="robots-section">
        <h3>Robots In Inventory</h3>
        <% @robots.each do |robot| %>
          <ul>
            <% unless robot.pending %>
              <li>
                <%= link_to robot.designation, robot %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </section>
    </div><!-- end tab-pane -->

    <div class="tab-pane" id="tab3">

      <section class="robots-section">
        <h3>In Queue</h3>
        <% @robots.each do |robot| %>
          <ul>
            <% if robot.pending %>
              <li>
                <%= link_to robot.model_no, robot %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </section>

    </div><!-- end tab-pane -->

  </div><!-- end tab-content -->
</div>
</main>

app/views/robots/index_customer.html.erb
<% robots = get_inventory %>
<% manufacturers = get_manufacturers %>
<div class="container">
<ul class="nav nav-tabs">
  <li class="active"><a href="#tab1" data-toggle="tab">View By Manufacturers</a></li>
  <li><a href="#tab2" data-toggle="tab">View All</a></li>
</ul>

<div class="tab-content">

  <div class="tab-pane active" id="tab1">
    <section class="robots-section">
      <h3>Manufacturers</h3>
      <% manufacturers.each do |manufacturer| %>
        <ul>
          <li class="manufacturer-store">
          <%= link_to manufacturer.name, manufacturer, remote: true, class: 'manufacturer-link' %>
          </li>
        </ul>
      <% end %>
    </section>
  </div><!-- end tab-pane -->

  <div class="tab-pane" id="tab2">
    <section class="robots-section">
      <h3>Robots In Inventory</h3>
      <% robots.each do |robot| %>
        <ul>
          <% unless robot.pending %>
            <li>
              <%= link_to robot.designation, robot, remote: true, class: 'robot-buy-link'%>
            </li>
          <% end %>
        </ul>
      <% end %>
    </section>
  </div>
</div>

</div>

app/views/robots/show.html.erb
<nav class="home_link">
  <h1><%= link_to 'PSKLRMRFI', robots_path, class: 'home-link' %></h1>
</nav>

  <section class="individual-item-container">
    <div class="center-show-info">
      <% if @robot.pending %>
        <h1>Pending Bot</h1>
      <% else %>
        <% if !@robot.designation.nil? %>
        <div class="robot_show_title">
          Your Robot
          </div>
          <div class='robot_show_designation'>
            "<%= @robot.designation%>"
          </div>
        <% end %>
      
    <% end %>

    <div class='robot_show_model_no'>
        Model No: <%= @robot.model_no %>
    </div>

    <div>
      Weight: <%= @robot.weight%> Tons
    </div>

    <div>
      Height: <%= @robot.height%> Yds
    </div>

    <div>
      Price: $<%= sprintf('%.2f', @robot.price) %>
    </div>

  <% if @robot.pending == false %>
    <%= form_tag("/robots/#{@robot.id}/edit", method: "GET") do %>
      <%= submit_tag("Re-designate")%>
    <% end %>
    <%= form_tag("/robots/#{@robot.id}", method: "DELETE") do %>
      <%= submit_tag("Remove")%>
    <% end %>
  <% else %>
    <%= form_tag("/robots/#{@robot.id}/edit", method: "GET") do %>
      <%= submit_tag("Add to Inventory") %>
    <% end %>
  <% end %>
  </section>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary form_btn" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class='registration_form'>
  <h1 class="form_header">Update your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>

        <%= f.label :usernname %>
        <%= f.text_field :username %>

        <%= f.label :email, "Update Email Address" %>
        <%= f.email_field :email %>

        <%= f.label :password, "New Password" %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm New Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='registration_form'>
  <h1 class="form_header">Sign Up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.erb
<% if current_user %>
<div class='center-align'>
  <a class='button' href="/">Home Page</a>
</div>

<footer class='center-no-pad'>
    <form class='button' action="/sessions" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Logout">
    </form>
</footer>
<% end %>